export const students = [
  { value: "santiago-rodriguez", label: "Santiago Rodríguez" },
  { value: "valentina-morales", label: "Valentina Morales" },
  { value: "matias-fernandez", label: "Matías Fernández" },
  { value: "camila-perez", label: "Camila Pérez" },
  { value: "daniel-martinez", label: "Daniel Martínez" },
  { value: "sofia-castano", label: "Sofía Castaño" },
  { value: "nicolas-gutierrez", label: "Nicolás Gutiérrez" },
  { value: "isabella-velasquez", label: "Isabella Velásquez" },
  { value: "juan-diaz", label: "Juan Díaz" },
  { value: "maria-jimenez", label: "María Jiménez" },
  { value: "alejandro-rojas", label: "Alejandro Rojas" },
  { value: "laura-uribe", label: "Laura Uribe" },
  { value: "pablo-torres", label: "Pablo Torres" },
  { value: "valeria-ramirez", label: "Valeria Ramírez" },
  { value: "sebastian-moreno", label: "Sebastián Moreno" },
  { value: "camila-herrera", label: "Camila Herrera" },
  { value: "felipe-rodriguez", label: "Felipe Rodríguez" },
  { value: "natalia-soto", label: "Natalia Soto" },
  { value: "andres-ortiz", label: "Andrés Ortiz" },
  { value: "isabella-gonzalez", label: "Isabella González" },
];
