export const teachers = [
  { value: "juan-perez", label: "Juan Pérez" },
  { value: "maria-gomez", label: "María Gómez" },
  { value: "jose-rodriguez", label: "José Rodríguez" },
  { value: "ana-martinez", label: "Ana Martínez" },
  { value: "luis-lopez", label: "Luis López" },
  { value: "carla-sanchez", label: "Carla Sánchez" },
  { value: "pablo-morales", label: "Pablo Morales" },
  { value: "laura-castro", label: "Laura Castro" },
  { value: "carlos-martinez", label: "Carlos Martínez" },
  { value: "sofia-hernandez", label: "Sofía Hernández" },
  { value: "andres-garcia", label: "Andrés García" },
  { value: "valeria-moreno", label: "Valeria Moreno" },
  { value: "sebastian-ruiz", label: "Sebastián Ruiz" },
  { value: "camila-bermudez", label: "Camila Bermúdez" },
  { value: "david-ortiz", label: "David Ortiz" },
  { value: "paola-ramirez", label: "Paola Ramírez" },
  { value: "nicolas-vargas", label: "Nicolás Vargas" },
  { value: "isabella-munoz", label: "Isabella Muñoz" },
  { value: "felipe-jimenez", label: "Felipe Jiménez" },
  { value: "natalia-cardenas", label: "Natalia Cárdenas" },
];
