import { FormNewLesson, FormNewUser, Header } from "@/components";
import { SideBarMenu } from "@/components/SideBarMenu";

export const metadata = {
  title: "Plataforma para estudiantes y profesores",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <div className="flex">
        {/* Sidebar */}

        <SideBarMenu />
        {/* Main Content */}
        <div className="w-full">
          {/* Page Content */}
          <FormNewUser />
          <FormNewLesson />
          <main className="p-2">{children}</main>
        </div>
      </div>
    </>
  );
}
